# Normalization

In [8]:
import numpy as np # range is constrained between  0 and 1
from sklearn.preprocessing import MinMaxScaler

data = np.array([[1,2,3],[4,5,6],[7,8,9]])

scaler = MinMaxScaler()

normalized = scaler.fit_transform(data)

print(f'Normalized data:\n {normalized}')

Normalized data:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


# Standardization

In [9]:
import numpy as np # range is constrained
from sklearn.preprocessing import StandardScaler

data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

scaler = StandardScaler()
standard_data = scaler.fit_transform(data)
print("standar data \n", standard_data)

standar data 
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
